package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"log"

	"github.com/go-graph-booklets/server/gqlgen-todos/auth"
	"github.com/go-graph-booklets/server/gqlgen-todos/graph/model"
	"github.com/google/uuid"
)

// ID is the resolver for the id field.
func (r *bookResolver) ID(ctx context.Context, obj *model.Book) (string, error) {
	return obj.ID.String(), nil
}

// CreatedAt is the resolver for the created_at field.
func (r *bookResolver) CreatedAt(ctx context.Context, obj *model.Book) (string, error) {
	return obj.CreatedAt.String(), nil
}

// CreateBook is the resolver for the createBook field.
func (r *mutationResolver) CreateBook(ctx context.Context, name string, publisherID string, authorID string) (*model.Book, error) {
	publisherUUID, err := uuid.Parse(publisherID)
	if err != nil {
		return nil, err
	}

	authorUUID, err := uuid.Parse(authorID)
	if err != nil {
		return nil, err
	}

	newBook, err := r.Repo.CreateBook(name, publisherUUID, authorUUID)
	return &newBook, err
}

// UpdateBookName is the resolver for the updateBookName field.
func (r *mutationResolver) UpdateBookName(ctx context.Context, id string, newBookName string) (*model.Book, error) {
	bookID, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}

	updatedBook, err := r.Repo.UpdateBookName(bookID, newBookName)
	return &updatedBook, err
}

// DeleteBook is the resolver for the deleteBook field.
func (r *mutationResolver) DeleteBook(ctx context.Context, id string) (*model.Book, error) {
	bookID, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}

	deletedBook, err := r.Repo.DeleteBook(bookID)
	return &deletedBook, err
}

// CreatePublisher is the resolver for the createPublisher field.
func (r *mutationResolver) CreatePublisher(ctx context.Context, name string, ownerID string) (*model.Publisher, error) {
	user := auth.ForContext(ctx)
	log.Println("User: ", user, "OwnerID: ", ownerID)
	if ownerID != user.ID.String() {
		return nil, fmt.Errorf("you can't create a publisher for another user")
	}
	log.Println("Creating publisher for user: ", user.Username)
	newPublisher, err := r.Repo.CreatePublisher(name, user.ID)
	if err != nil {
		log.Println(err)
		return nil, err
	}

	log.Println("Created publisher: ", newPublisher)
	return &newPublisher, nil
}

// DeletePublisher is the resolver for the deletePublisher field.
func (r *mutationResolver) DeletePublisher(ctx context.Context, id string) (*model.Publisher, error) {
	user := auth.ForContext(ctx)
	publisherID, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}

	targetPublisher, err := r.Repo.GetPublisherById(publisherID)
	if err != nil {
		return nil, err
	}

	if targetPublisher.Owner != user.ID {
		return nil, fmt.Errorf("Unauthorized")
	}

	deletedPublisher, err := r.Repo.DeletePublisher(publisherID)
	return &deletedPublisher, err
}

// UpdateUsername is the resolver for the updateUsername field.
func (r *mutationResolver) UpdateUsername(ctx context.Context, id string, username string, password string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: UpdateUsername - mutation"))
}

// ID is the resolver for the id field.
func (r *publisherResolver) ID(ctx context.Context, obj *model.Publisher) (string, error) {
	return obj.ID.String(), nil
}

// CreatedAt is the resolver for the created_at field.
func (r *publisherResolver) CreatedAt(ctx context.Context, obj *model.Publisher) (string, error) {
	return obj.CreatedAt.UTC().String(), nil
}

// Owner is the resolver for the owner field.
func (r *publisherResolver) Owner(ctx context.Context, obj *model.Publisher) (*model.User, error) {
	owner, err := r.Repo.GetUserById(obj.Owner)
	if err != nil {
		return nil, err
	}

	return &owner, nil
}

// Books is the resolver for the books field.
func (r *publisherResolver) Books(ctx context.Context, obj *model.Publisher) ([]*model.Book, error) {
	books, err := r.Repo.GetBooksByPublisherID(obj.ID)
	if err != nil {
		return nil, err
	}

	return books, nil
}

// Books is the resolver for the books field.
func (r *queryResolver) Books(ctx context.Context) ([]*model.Book, error) {
	// get all books
	books, err := r.Repo.GetBooks()
	if err != nil {
		return nil, err
	}
	return books, nil
}

// Book is the resolver for the book field.
func (r *queryResolver) Book(ctx context.Context, id string) (*model.Book, error) {
	bookID, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}

	book, err := r.Repo.GetBook(bookID)
	if err != nil {
		return nil, err
	}

	return &book, nil
}

// Publishers is the resolver for the publishers field.
func (r *queryResolver) Publishers(ctx context.Context) ([]*model.Publisher, error) {
	// get all publishers
	publishers, err := r.Repo.GetPublishers()
	if err != nil {
		return nil, err
	}
	return publishers, nil
}

// Publisher is the resolver for the publisher field.
func (r *queryResolver) Publisher(ctx context.Context, id string) (*model.Publisher, error) {
	publisherID, err := uuid.Parse(id)
	if err != nil {
		return nil, err
	}
	publisher, err := r.Repo.GetPublisherById(publisherID)
	if err != nil {
		return nil, err
	}

	return &publisher, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	panic(fmt.Errorf("not implemented: Users - users"))
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// ID is the resolver for the id field.
func (r *userResolver) ID(ctx context.Context, obj *model.User) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// CreatedAt is the resolver for the created_at field.
func (r *userResolver) CreatedAt(ctx context.Context, obj *model.User) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - created_at"))
}

// Books is the resolver for the books field.
func (r *userResolver) Books(ctx context.Context, obj *model.User) ([]*model.Book, error) {
	panic(fmt.Errorf("not implemented: Books - books"))
}

// Publishers is the resolver for the publishers field.
func (r *userResolver) Publishers(ctx context.Context, obj *model.User) ([]*model.Publisher, error) {
	panic(fmt.Errorf("not implemented: Publishers - publishers"))
}

// Book returns BookResolver implementation.
func (r *Resolver) Book() BookResolver { return &bookResolver{r} }

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Publisher returns PublisherResolver implementation.
func (r *Resolver) Publisher() PublisherResolver { return &publisherResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// User returns UserResolver implementation.
func (r *Resolver) User() UserResolver { return &userResolver{r} }

type bookResolver struct{ *Resolver }
type mutationResolver struct{ *Resolver }
type publisherResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type userResolver struct{ *Resolver }
