// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/google/uuid"
)

type CreateBookInput struct {
	Name        string    `json:"name"`
	AuthorID    uuid.UUID `json:"authorId"`
	PublisherID uuid.UUID `json:"publisherId"`
}

type CreatePublisherInput struct {
	Name    string    `json:"name"`
	OwnerID uuid.UUID `json:"ownerId"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateBookInput struct {
	BookID      uuid.UUID `json:"bookId"`
	Name        string    `json:"name"`
	AuthorID    uuid.UUID `json:"authorId"`
	PublisherID uuid.UUID `json:"publisherId"`
}

type UpdatePublisherInput struct {
	Name *string `json:"name,omitempty"`
}
