// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateBookInput struct {
	Name        string `json:"name"`
	AuthorID    string `json:"authorId"`
	PublisherID string `json:"publisherId"`
}

type CreatePublisherInput struct {
	Name    string `json:"name"`
	OwnerID string `json:"ownerId"`
}

type Mutation struct {
}

type Query struct {
}

type UpdateBookInput struct {
	BookID      string `json:"bookId"`
	Name        string `json:"name"`
	AuthorID    string `json:"authorId"`
	PublisherID string `json:"publisherId"`
}

type UpdatePublisherInput struct {
	Name *string `json:"name,omitempty"`
}
